config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'task/:id', to: 'tasks#show', as: :task
  get 'task/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'task/:id', to: 'tasks#update'
  delete 'task/:id', to: 'tasks#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
  </head>

  <body>
    <div class="nav-bar">
      <div class="btn btn primary">
        <%= link_to "Articles", articles_path %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed, {},'true', 'false' %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Task Manager</h1>

<h2>Here is the list of the tasks</h2>
<ol>
<% @tasks.each do |task| %>
  <li><%= check_box_tag 'completed', 'true', task.completed %> <%= link_to task.title, task_path(task) %>
<%= link_to task_path(task),method: :delete, data: { confirm: "Are you sure?" } do %>
  <i class="fas fa-dumpster"></i>
<% end %>
  </li>
  <% end %>
</ol>

<p><%= link_to "Add a new task", new_path %></p>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Here is the details of your task</h1>

<p><%= @task.title %></p>
<p><%= @task.details %></p>
<p><i>Completed ?<%= check_box_tag 'completed', 'true', @task.completed %> </p>
<p><%= link_to "Edit task", task_edit_path %></p>
<p><%= link_to "Go back to your task list", tasks_path %></p>